import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientLayout"; // Import the new ClientLayout component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tamaduni",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-[1600px] mx-auto p-0 px-4  ${inter.className}`}>
        <ClientLayout>{children}</ClientLayout> {/* Wrap with ClientLayout */}
      </body>
    </html>
  );
}
